- name: install postgres
  apt: pkg=$item state=latest install_recommends=no
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Set pg_hba access
  template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/9.1/main/pg_hba.conf owner=postgres group=postgres mode=0644
  notify:
    - restart postgresql
